name: rushhour
version: 0.0.0
description: Solves your rush hour puzzles!
authors:
- Kasper Peulen <kasperpeulen@gmail.com>
environment:
  sdk: ^1.12.0
dependencies:
  test: ^0.12.5+1
  testcase: ^0.1.0
